import { getProducts } from "@/lib/firestore";
import type { FirestoreProduct } from "@/lib/firestore";
import { useEffect, useState } from "react";

const PRODUCT_IMAGES = [
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm-019d216e-a4ca-73de-8587-623abfcbffe4-7.jpeg",
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_3-019d216e-808e-76ab-9899-e35652a1a476-1.jpeg",
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.25.59_pm_2-019d216e-8655-75c4-90fc-8395dd1d83f6-5.jpeg",
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_1-019d216e-8646-71ec-934b-8a0238624d7b-4.jpeg",
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.01_pm-019d216e-8e15-725f-8e61-e65fba3f419a-6.jpeg",
  "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_2-019d216e-83cf-74e1-9f96-e81a94b4784d-2.jpeg",
];

export const STATIC_PRODUCTS: FirestoreProduct[] = [
  // User product images
  {
    id: "101",
    name: "Barrier Repair Cream",
    description: "Barrier Repair Cream",
    price: 499,
    originalPrice: 599,
    rating: 4.7,
    reviews: 120,
    imageUrl: "/product - Barrier Repair Cream.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Hydration"],
    category: "Moisturizer",
    stock: 50,
  },
  {
    id: "102",
    name: "Barrier Repair Cleanser",
    description: "Barrier Repair Cleanser",
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviews: 80,
    imageUrl: "/product - Barrier Repair cleaneser.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Hydration"],
    category: "Cleanser",
    stock: 50,
  },
  {
    id: "103",
    name: "Coconut Body Lotion",
    description: "Coconut Body Lotion",
    price: 349,
    originalPrice: 449,
    rating: 4.5,
    reviews: 60,
    imageUrl: "/product - coconut body lotion.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Hydration"],
    category: "Body Lotion",
    stock: 50,
  },
  {
    id: "104",
    name: "Glutathione Cleanser",
    description: "Glutathione Cleanser",
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    reviews: 98,
    imageUrl: "/product - glutathyone cleanser.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Brightening"],
    category: "Cleanser",
    stock: 50,
  },
  {
    id: "105",
    name: "Grapeseed Body Lotion",
    description: "Grapeseed Body Lotion",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    reviews: 87,
    imageUrl: "/product - grapeseed body lotion.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Hydration"],
    category: "Body Lotion",
    stock: 50,
  },
  {
    id: "106",
    name: "Niacinamide Serum",
    description: "Niacinamide Serum",
    price: 599,
    originalPrice: 699,
    rating: 4.9,
    reviews: 150,
    imageUrl: "/product - niacinamide serum.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Anti-Aging"],
    category: "Serum",
    stock: 50,
  },
  {
    id: "107",
    name: "Niacinamide Sunscreen 80ml",
    description: "Niacinamide Sunscreen 80ml",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    reviews: 90,
    imageUrl: "/product - niacinamide sunscreen 80ml.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Sun Protection"],
    category: "Sunscreen",
    stock: 50,
  },
  {
    id: "108",
    name: "Niacinamide Sunscreen",
    description: "Niacinamide Sunscreen",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    reviews: 90,
    imageUrl: "/product - niacinamide sunscreen.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Sun Protection"],
    category: "Sunscreen",
    stock: 50,
  },
  {
    id: "109",
    name: "Niacinamide Toner",
    description: "Niacinamide Toner",
    price: 299,
    originalPrice: 399,
    rating: 4.5,
    reviews: 65,
    imageUrl: "/product - niacinamide toner.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Hydration"],
    category: "Toner",
    stock: 50,
  },
  {
    id: "110",
    name: "Skin Brightening Cream",
    description: "Skin Brightening Cream",
    price: 499,
    originalPrice: 599,
    rating: 4.7,
    reviews: 110,
    imageUrl: "/product - Skin Briughting Cream.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Brightening"],
    category: "Moisturizer",
    stock: 50,
  },
  {
    id: "111",
    name: "Vitamin C Cleanser",
    description: "Vitamin C Cleanser",
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    reviews: 105,
    imageUrl: "/product - vitamin c cleanser.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Brightening"],
    category: "Cleanser",
    stock: 50,
  },
  {
    id: "112",
    name: "Vitamin C Cream",
    description: "Vitamin C Cream",
    price: 499,
    originalPrice: 599,
    rating: 4.7,
    reviews: 110,
    imageUrl: "/product - vitamin c cream.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Brightening"],
    category: "Moisturizer",
    stock: 50,
  },
  {
    id: "113",
    name: "Vitamin C Serum",
    description: "Vitamin C Serum",
    price: 599,
    originalPrice: 699,
    rating: 4.9,
    reviews: 150,
    imageUrl: "/product - vitamin c serum.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Brightening"],
    category: "Serum",
    stock: 50,
  },
  {
    id: "114",
    name: "Vitamin C Sunscreen",
    description: "Vitamin C Sunscreen",
    price: 349,
    originalPrice: 449,
    rating: 4.6,
    reviews: 90,
    imageUrl: "/product - vitamin c sunscreen.jpg",
    badge: "New",
    skinType: "All Skin",
    concerns: ["Sun Protection"],
    category: "Sunscreen",
    stock: 50,
  },
];

export function useProducts() {
  const [products, setProducts] = useState<FirestoreProduct[]>([]);
  const [loading, setLoading] = useState(true);
  const [isFirestoreData, setIsFirestoreData] = useState(false);

  useEffect(() => {
    getProducts()
      .then((data) => {
        if (data.length > 0) {
          setProducts(data);
          setIsFirestoreData(true);
        } else {
          setProducts(STATIC_PRODUCTS);
        }
      })
      .catch(() => {
        setProducts(STATIC_PRODUCTS);
      })
      .finally(() => setLoading(false));
  }, []);

  return { products, loading, isFirestoreData };
}












// import { getProducts } from "@/lib/firestore";
// import type { FirestoreProduct } from "@/lib/firestore";
// import { useEffect, useState } from "react";

// const PRODUCT_IMAGES = [
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm-019d216e-a4ca-73de-8587-623abfcbffe4-7.jpeg",
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_3-019d216e-808e-76ab-9899-e35652a1a476-1.jpeg",
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.25.59_pm_2-019d216e-8655-75c4-90fc-8395dd1d83f6-5.jpeg",
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_1-019d216e-8646-71ec-934b-8a0238624d7b-4.jpeg",
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.01_pm-019d216e-8e15-725f-8e61-e65fba3f419a-6.jpeg",
//   "/assets/uploads/whatsapp_image_2026-03-21_at_8.26.00_pm_2-019d216e-83cf-74e1-9f96-e81a94b4784d-2.jpeg",
// ];

// export const STATIC_PRODUCTS: FirestoreProduct[] = [
//   // User product images
//   {
//     id: "101",
//     name: "Barrier Repair Cream",
//     description: "Barrier Repair Cream",
//     price: 499,
//     originalPrice: 599,
//     rating: 4.7,
//     reviews: 120,
//     imageUrl: "/product - Barrier Repair Cream.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Hydration",
//     category: "Moisturizer",
//     stock: 50,
//   },
//   {
//     id: "102",
//     name: "Barrier Repair Cleanser",
//     description: "Barrier Repair Cleanser",
//     price: 399,
//     originalPrice: 499,
//     rating: 4.6,
//     reviews: 80,
//     imageUrl: "/product - Barrier Repair cleaneser.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Hydration",
//     category: "Cleanser",
//     stock: 50,
//   },
//   {
//     id: "103",
//     name: "Coconut Body Lotion",
//     description: "Coconut Body Lotion",
//     price: 349,
//     originalPrice: 449,
//     rating: 4.5,
//     reviews: 60,
//     imageUrl: "/product - coconut body lotion.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Hydration",
//     category: "Body Lotion",
//     stock: 50,
//   },
//   {
//     id: "104",
//     name: "Glutathione Cleanser",
//     description: "Glutathione Cleanser",
//     price: 399,
//     originalPrice: 499,
//     rating: 4.8,
//     reviews: 98,
//     imageUrl: "/product - glutathyone cleanser.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 50,
//   },
//   {
//     id: "105",
//     name: "Grapeseed Body Lotion",
//     description: "Grapeseed Body Lotion",
//     price: 349,
//     originalPrice: 449,
//     rating: 4.6,
//     reviews: 87,
//     imageUrl: "/product - grapeseed body lotion.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Hydration",
//     category: "Body Lotion",
//     stock: 50,
//   },
//   {
//     id: "106",
//     name: "Niacinamide Serum",
//     description: "Niacinamide Serum",
//     price: 599,
//     originalPrice: 699,
//     rating: 4.9,
//     reviews: 150,
//     imageUrl: "/product - niacinamide serum.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Anti-Aging",
//     category: "Serum",
//     stock: 50,
//   },
//   {
//     id: "107",
//     name: "Niacinamide Sunscreen 80ml",
//     description: "Niacinamide Sunscreen 80ml",
//     price: 349,
//     originalPrice: 449,
//     rating: 4.6,
//     reviews: 90,
//     imageUrl: "/product - niacinamide sunscreen 80ml.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Sun Protection",
//     category: "Sunscreen",
//     stock: 50,
//   },
//   {
//     id: "108",
//     name: "Niacinamide Sunscreen",
//     description: "Niacinamide Sunscreen",
//     price: 349,
//     originalPrice: 449,
//     rating: 4.6,
//     reviews: 90,
//     imageUrl: "/product - niacinamide sunscreen.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Sun Protection",
//     category: "Sunscreen",
//     stock: 50,
//   },
//   {
//     id: "109",
//     name: "Niacinamide Toner",
//     description: "Niacinamide Toner",
//     price: 299,
//     originalPrice: 399,
//     rating: 4.5,
//     reviews: 65,
//     imageUrl: "/product - niacinamide toner.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Hydration",
//     category: "Toner",
//     stock: 50,
//   },
//   {
//     id: "110",
//     name: "Skin Brightening Cream",
//     description: "Skin Brightening Cream",
//     price: 499,
//     originalPrice: 599,
//     rating: 4.7,
//     reviews: 110,
//     imageUrl: "/product - Skin Briughting Cream.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Moisturizer",
//     stock: 50,
//   },
//   {
//     id: "111",
//     name: "Vitamin C Cleanser",
//     description: "Vitamin C Cleanser",
//     price: 399,
//     originalPrice: 499,
//     rating: 4.8,
//     reviews: 105,
//     imageUrl: "/product - vitamin c cleanser.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 50,
//   },
//   {
//     id: "112",
//     name: "Vitamin C Cream",
//     description: "Vitamin C Cream",
//     price: 499,
//     originalPrice: 599,
//     rating: 4.7,
//     reviews: 110,
//     imageUrl: "/product - vitamin c cream.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Moisturizer",
//     stock: 50,
//   },
//   {
//     id: "113",
//     name: "Vitamin C Serum",
//     description: "Vitamin C Serum",
//     price: 599,
//     originalPrice: 699,
//     rating: 4.9,
//     reviews: 150,
//     imageUrl: "/product - vitamin c serum.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Serum",
//     stock: 50,
//   },
//   {
//     id: "114",
//     name: "Vitamin C Sunscreen",
//     description: "Vitamin C Sunscreen",
//     price: 349,
//     originalPrice: 449,
//     rating: 4.6,
//     reviews: 90,
//     imageUrl: "/product - vitamin c sunscreen.jpg",
//     badge: "New",
//     skinType: "All Skin",
//     concern: "Sun Protection",
//     category: "Sunscreen",
//     stock: 50,
//   },
//   {
//     id: "1",
//     name: "Niacinamide 10% Serum",
//     description: "Minimises pores & controls oil",
//     price: 649,
//     originalPrice: 849,
//     rating: 4.5,
//     reviews: 1240,
//     imageUrl: PRODUCT_IMAGES[0],
//     badge: "Bestseller",
//     skinType: "Oily",
//     concern: "Acne",
//     category: "Serum",
//     stock: 50,
//   },
//   {
//     id: "2",
//     name: "Vitamin C+E Cleanser",
//     description: "Brightening gentle foam cleanser",
//     price: 499,
//     originalPrice: 649,
//     rating: 4.3,
//     reviews: 876,
//     imageUrl: PRODUCT_IMAGES[1],
//     badge: "",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 80,
//   },
//   {
//     id: "3",
//     name: "Rice Water Toner",
//     description: "Soothing & hydrating essence",
//     price: 549,
//     originalPrice: 699,
//     rating: 4.6,
//     reviews: 1050,
//     imageUrl: PRODUCT_IMAGES[2],
//     badge: "New",
//     skinType: "Sensitive",
//     concern: "Hydration",
//     category: "Toner",
//     stock: 60,
//   },
//   {
//     id: "4",
//     name: "SPF 50+ Sunscreen",
//     description: "Lightweight, no white cast",
//     price: 799,
//     originalPrice: 999,
//     rating: 4.7,
//     reviews: 2100,
//     imageUrl: PRODUCT_IMAGES[3],
//     badge: "Bestseller",
//     skinType: "All Skin",
//     concern: "Anti-Aging",
//     category: "Sunscreen",
//     stock: 100,
//   },
//   {
//     id: "5",
//     name: "Vitamin C Moisturizer",
//     description: "Brightens & deeply hydrates",
//     price: 899,
//     originalPrice: 1199,
//     rating: 4.4,
//     reviews: 540,
//     imageUrl: PRODUCT_IMAGES[4],
//     badge: "",
//     skinType: "Dry",
//     concern: "Brightening",
//     category: "Moisturizer",
//     stock: 40,
//   },
//   {
//     id: "6",
//     name: "Glutathione Cleanser",
//     description: "Even tone, glass skin glow",
//     price: 599,
//     originalPrice: 749,
//     rating: 4.5,
//     reviews: 780,
//     imageUrl: PRODUCT_IMAGES[5],
//     badge: "",
//     skinType: "Combination",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 70,
//   },
//   {
//     id: "7",
//     name: "Niacinamide Face Serum",
//     description: "Minimises pores & controls oil",
//     price: 629,
//     originalPrice: 849,
//     rating: 4.5,
//     reviews: 1310,
//     imageUrl: PRODUCT_IMAGES[0],
//     badge: "Bestseller",
//     skinType: "Oily",
//     concern: "Acne",
//     category: "Serum",
//     stock: 55,
//   },
//   {
//     id: "8",
//     name: "Brightening Cleanser",
//     description: "Brightening gentle foam cleanser",
//     price: 479,
//     originalPrice: 649,
//     rating: 4.3,
//     reviews: 910,
//     imageUrl: PRODUCT_IMAGES[1],
//     badge: "",
//     skinType: "All Skin",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 85,
//   },
//   {
//     id: "9",
//     name: "Rose Water Toner",
//     description: "Soothing & hydrating essence",
//     price: 529,
//     originalPrice: 699,
//     rating: 4.6,
//     reviews: 1120,
//     imageUrl: PRODUCT_IMAGES[2],
//     badge: "New",
//     skinType: "Sensitive",
//     concern: "Hydration",
//     category: "Toner",
//     stock: 65,
//   },
//   {
//     id: "10",
//     name: "SPF 60 PA++++ Sunscreen",
//     description: "Lightweight, no white cast",
//     price: 749,
//     originalPrice: 999,
//     rating: 4.7,
//     reviews: 2250,
//     imageUrl: PRODUCT_IMAGES[3],
//     badge: "Bestseller",
//     skinType: "All Skin",
//     concern: "Anti-Aging",
//     category: "Sunscreen",
//     stock: 110,
//   },
//   {
//     id: "11",
//     name: "Glow Moisturizer",
//     description: "Brightens & deeply hydrates",
//     price: 869,
//     originalPrice: 1199,
//     rating: 4.4,
//     reviews: 598,
//     imageUrl: PRODUCT_IMAGES[4],
//     badge: "",
//     skinType: "Dry",
//     concern: "Brightening",
//     category: "Moisturizer",
//     stock: 45,
//   },
//   {
//     id: "12",
//     name: "Glass Skin Cleanser",
//     description: "Even tone, glass skin glow",
//     price: 579,
//     originalPrice: 749,
//     rating: 4.5,
//     reviews: 845,
//     imageUrl: PRODUCT_IMAGES[5],
//     badge: "New",
//     skinType: "Combination",
//     concern: "Brightening",
//     category: "Cleanser",
//     stock: 75,
//   },
// ];

// export function useProducts() {
//   const [products, setProducts] = useState<FirestoreProduct[]>([]);
//   const [loading, setLoading] = useState(true);
//   const [isFirestoreData, setIsFirestoreData] = useState(false);

//   useEffect(() => {
//     getProducts()
//       .then((data) => {
//         if (data.length > 0) {
//           // Sort by 'order' field if present
//           data.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
//           setProducts(data);
//           setIsFirestoreData(true);
//         } else {
//           setProducts(STATIC_PRODUCTS);
//         }
//       })
//       .catch(() => {
//         setProducts(STATIC_PRODUCTS);
//       })
//       .finally(() => setLoading(false));
//   }, []);

//   return { products, loading, isFirestoreData };
// }

















